version: '2'
services:
  discovery:
    image: binblee/discovery-server
    ports:
      - "8761:8761"
  config-server:
    image: binblee/config-server
    ports:
      - "8888:8888"
  gateway:
    image: binblee/gateway
    ports:
      - "8080:8080"
    links:
      - discovery
  foo:
    image: binblee/foo
    links:
      - discovery
      - config-server
  bar:
    image: binblee/bar
    links:
      - discovery
  foobar:
    image: binblee/foobar
    links:
      - discovery
